<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>companies-house-parent</artifactId>
        <groupId>uk.gov.companieshouse</groupId>
        <version>2.1.15</version>
        <relativePath/>
    </parent>

    <artifactId>docs.developer.ch.gov.uk</artifactId>
    <version>unversioned</version>
    <packaging>jar</packaging>
    <name>docs.developer.ch.gov.uk</name>
    <description>Static general documentation content</description>

    <properties>

        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <home.url/>

        <!-- Internal CH Dependency Versions       -->
        <!-- Source: https://github.com/companieshouse/structured-logging/releases -->
        <structured-logging.version>4.0.1</structured-logging.version>
        <!-- Source: https://github.com/companieshouse/common-web-java/releases -->
        <common-web-java.version>5.0.4</common-web-java.version>
        <!-- Source: https://github.com/companieshouse/java-session-handler/releases -->
        <java-session-handler.version>4.1.23</java-session-handler.version>
        <!-- Source: https://github.com/companieshouse/web-security-java/releases -->
        <web-security-java.version>3.1.19</web-security-java.version>

        <!-- Managed Dependency Versions        -->
        <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot -->
        <spring-boot.version>4.1.0</spring-boot.version>
        <!-- Source: https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter -->
        <mockito-junit-jupiter.version>5.23.0</mockito-junit-jupiter.version>
        <!-- Source: https://mvnrepository.com/artifact/nz.net.ultraq.thymeleaf/thymeleaf-layout-dialect -->
        <thymeleaf-layout-dialect.version>4.0.1</thymeleaf-layout-dialect.version>
        <!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j -->
        <log4j.version>2.26.1</log4j.version>
        <!-- Source: https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-bom -->
        <opentelemetry.version>2.30.0</opentelemetry.version>
        <!-- Source: https://mvnrepository.com/artifact/org.apache.tomcat.embed/tomcat-embed-core -->
        <tomcat.version>11.0.24</tomcat.version>

        <!-- Plugin Versions       -->
        <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
        <maven-surefire-plugin.version>3.5.6</maven-surefire-plugin.version>
        <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <!-- Source: https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin -->
        <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>
        <!-- Source: https://mvnrepository.com/artifact/com.google.cloud.tools/jib-maven-plugin -->
        <jib-maven-plugin.version>3.5.2</jib-maven-plugin.version>

    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom</artifactId>
                <version>${opentelemetry.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.20.0</version>
            </dependency>

            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>${tomcat.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-websocket</artifactId>
                <version>${tomcat.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!--  Spring Modules-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-opentelemetry</artifactId>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-logback-appender-1.0 -->
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-logback-appender-1.0</artifactId>
            <version>${opentelemetry.version}-alpha</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <artifactId>thymeleaf-layout-dialect</artifactId>
            <groupId>nz.net.ultraq.thymeleaf</groupId>
        </dependency>

        <!-- Companies House dependencies -->
        <dependency>
            <artifactId>structured-logging</artifactId>
            <groupId>uk.gov.companieshouse</groupId>
            <version>${structured-logging.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <artifactId>common-web-java</artifactId>
            <groupId>uk.gov.companieshouse</groupId>
            <version>${common-web-java.version}</version>
        </dependency>

        <dependency>
            <artifactId>java-session-handler</artifactId>
            <groupId>uk.gov.companieshouse</groupId>
            <version>${java-session-handler.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <artifactId>web-security-java</artifactId>
            <groupId>uk.gov.companieshouse</groupId>
            <version>${web-security-java.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <artifactId>mockito-junit-jupiter</artifactId>
            <groupId>org.mockito</groupId>
            <version>${mockito-junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <mainClass>uk.gov.ch.developer.docs.DocsWebApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib-maven-plugin.version}</version>
                <configuration>
                    <from>
                        <image>416670754337.dkr.ecr.eu-west-2.amazonaws.com/ci-corretto-build-21:latest</image>
                    </from>
                    <to>
                        <image>416670754337.dkr.ecr.eu-west-2.amazonaws.com/docs.developer.ch.gov.uk</image>
                    </to>
                    <container>
                        <expandClasspathDependencies>true</expandClasspathDependencies>
                    </container>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <environmentVariables>
                        <CACHE_POOL_SIZE>10</CACHE_POOL_SIZE>
                        <CACHE_SERVER>localhost:1234</CACHE_SERVER>
                        <COOKIE_DOMAIN>.companieshouse.gov.uk</COOKIE_DOMAIN>
                        <COOKIE_NAME>abc</COOKIE_NAME>
                        <COOKIE_SECRET>iamasecret</COOKIE_SECRET>
                        <DEFAULT_SESSION_EXPIRATION>3600</DEFAULT_SESSION_EXPIRATION>
                        <HUMAN_LOG>1</HUMAN_LOG>
                        <REDIRECT_URI>/</REDIRECT_URI>
                        <account.url>//</account.url>
                        <cdn.url>//</cdn.url>
                        <chs.url>//</chs.url>
                        <DEVELOPER_URL>/dev-hub</DEVELOPER_URL>
                        <createAccount.url>${home.url}/create-account</createAccount.url>
                        <developerGuidelines.url>${home.url}/developer-guidelines</developerGuidelines.url>
                        <developerSpecs.url>//</developerSpecs.url>
                        <gettingStarted.url>${home.url}/getting-started</gettingStarted.url>
                        <home.url>${home.url}</home.url>
                        <howToCreateApplication.path>//</howToCreateApplication.path>
                        <howToCreateApplication.url>//</howToCreateApplication.url>
                        <manageApplications.url>${home.url}/manage-applications</manageApplications.url>
                        <pageNotFound.path>dev-hub/error/404Error</pageNotFound.path>
                        <piwik.siteId>//</piwik.siteId>
                        <piwik.url>//</piwik.url>
                    </environmentVariables>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
            </plugin>

        </plugins>
    </build>
</project>
